# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.17
_src_path: gh:westerveltco/django-twc-package
author_email: josh@joshthomas.dev
author_name: Josh Thomas
current_version: 0.11.0
django_versions:
- '4.2'
- '5.0'
docs_domain: westervelt.dev
github_owner: westerveltco
github_repo: django-twc-toolbox
module_name: django_twc_toolbox
package_description: Various tools for Django projects at The Westervelt Company.
package_name: django-twc-toolbox
python_versions:
- '3.10'
- '3.11'
- '3.12'
test_django_main: true
versioning_scheme: SemVer
