name: release

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  pypi:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: check
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: westerveltco/setup-ci-action@v0
        with:
          python-version: "3.12"
          extra-python-dependencies: hatch
          use-uv: true

      - name: Build package
        run: |
          hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
